{% set version = "1.1.0" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-cffr
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/cffr_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/cffr/cffr_{{ version }}.tar.gz
  sha256: 7d919d3f4f1c888560879825c2ba38056721b280791e82d0d70116b029995c7a

build:
  noarch: generic
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-cli >=2.0.0
    - r-desc >=1.3.0
    - r-jsonlite >=1.7.2
    - r-jsonvalidate >=1.1.0
    - r-yaml >=2.2.1
  run:
    - r-base
    - r-cli >=2.0.0
    - r-desc >=1.3.0
    - r-jsonlite >=1.7.2
    - r-jsonvalidate >=1.1.0
    - r-yaml >=2.2.1

test:
  commands:
    - $R -e "library('cffr')"           # [not win]
    - "\"%R%\" -e \"library('cffr')\""  # [win]

about:
  home: https://docs.ropensci.org/cffr/
  dev_url: https://github.com/ropensci/cffr
  license: GPL-3.0-or-later
  summary: The Citation File Format version 1.2.0 <doi:10.5281/zenodo.5171937> is a human and machine readable file format which provides citation metadata for software. This package provides core utilities to generate and validate this metadata.
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3

extra:
  recipe-maintainers:
    - conda-forge/r
    - raivivek
